spring.application.name=rsis

# ===== DATABASE (Supabase PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.ndfzwfdofcnxkkibgare&password=[Rumahsakitintelligentsystem]
spring.datasource.username=postgres.ndfzwfdofcnxkkibgare
spring.datasource.password=Rumahsakitintelligentsystem
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== THYMELEAF =====
spring.thymeleaf.cache=false

# ===== APP PORT =====
server.port=8080